[[priority1]]
== Priority Area 1: Science and Research

*_Improving biodiversity evidence for scientific research and understanding_*

[[activity1-1]]
=== Activity 1.1: Drive mobilization and use of biodiversity data to support priority thematic areas of relevance

==== Projected outcomes for 2027

*	Knowledge gaps are reduced by consolidating data coverage across the thematic areas of relevance
*	GBIF’s relevance to research is enhanced, through increased recognition and uptake of GBIF* mediated data among researchers across additional scientific disciplines

==== Indicative tasks for 2024

*	Commission an update to the systematic review of GBIF use in research (https://doi.org/10.1073/pnas.2018093118[Heberling et al. 2020^]) to identify trends in research uses for the 2020-2024 periods, deepen the analysis of methods and analytical approaches, and inform future support for priority thematic areas of relevance
* Advance collaborative activities across new thematic areas of relevance based on recommendations from the Science Committee (currently identified as invasive alien species and agrobiodiversity) with support of identified experts in these areas
* Expand data flows relating to vectors of human disease, in particular malaria-related data through GBIF partnership in the https://www.gatesfoundation.org/about/committed-grants/2022/04/inv021972[Vector Atlas^] project, with additional data streams on non-malaria vectors as recommended by the https://www.gbif.org/news/4jj1iKMn5llVnM6cUr8Y2m/[GBIF task group on vectors of human diseases^]
* Strengthen and expand support and guidance on mobilizing DNA-derived data from a range of data holder types and scales, supported by data quality improvements, improved coverage of DNA-detected organisms in the GBIF taxonomic backbone, and alignment of guidance with the new GBIF data model

_Expected funding sources_: Salaried staff, core funds for external contracts and non-salary expenses, supplementary funds, https://www.gatesfoundation.org/[Bill & Melinda Gates Foundation^] (for Vector Atlas)

[[activity1-2]]
=== Activity 1.2: Advance GBIF’s contribution to latest biodiversity modelling approaches

==== Projected outcomes for 2027

* GBIF supports the evolution of fundamental data-driven biodiversity research and its application across methods, scales and disciplines in life and environmental sciences

==== Indicative tasks for 2024

* Consolidate prototype ‘digital twins’ dependent on and coordinated by GBIF through partnering with the BioDT project; support testing of prototype twins with user groups and links to key biodiversity data infrastructures; build cross-initiative and cross-project connections (as with the B3 project) though data and service co-dependencies.
* Improve GBIF’s capabilities to manage data streams from key ecological data infrastructures and monitoring programmes, through application of the diversified data model to accommodate richer data including absences based on complete species lists. Workshop planned for 2024 with key partners involved in the TDWG Humboldt Extension, to design data flows and outputs.

NOTE: Based on the experience of 2023, it is proposed to discontinue Activity 1.3 (Support open science principles) as a separate activity within the Science and Research priority area. Significant progress has been made e.g. in the recognition of GBIF as a Global Core Biodata Resource, and inclusion of GBIF in the list of core data infrastructures supporting UNESCO open science recommendation. Follow-up of other tasks within this Activity, e.g. engagement with UNESCO/OECD and implementation of CARE principles, are redistributed to priority areas 2 and 3.
