[[priority1]]
== Priority Area 1: Science and Research

*_Improving biodiversity evidence for scientific research and understanding_*

[[activity1-1]]
=== Activity 1.1: Drive mobilization and use of biodiversity data to support priority thematic areas of relevance

==== Projected outcomes for 2027

-	Knowledge gaps are reduced by consolidating data coverage across the thematic areas of relevance
-	GBIF’s relevance to research is enhanced, through increased recognition and uptake of GBIF- mediated data among researchers across additional scientific disciplines

==== Indicative tasks for 2024

-	Commission an update to the systematic review of GBIF use in research
- …

[[activity1-2]]
=== Activity 1.2: Advance GBIF’s contribution to latest biodiversity modelling approaches

==== Projected outcomes for 2027

- GBIF supports the evolution of fundamental data-driven biodiversity research and its application across methods, scales and disciplines in life and environmental sciences

==== Indicative tasks for 2024

- Consolidate prototype ‘digital twins’
- …
