[[budget]]
== Indicative Budget for 2024

This draft budget intends to give a broad overview of expected GBIF income and expenses in 2024.  This includes funds for Work Programme activities as well as Secretariat administration and governance. It also delineates funding from Basic Financial Contributions (Core) and Supplementary Funds

The Secretariat welcomes contributions to the Special Purpose Funds (SPF) aligned to each Priority Area. These are contributions above expected national contributions that would accelerate progress in specific Activity Areas.  Through this mechanism Participants can prioritize efforts to meet national or broader GBIF priorities in WP24. Specific Indicatives tasks could be developed to meet these SPF goals.

=== WP2024

In 2024 the Secretariat expects to receive 4.2M euro in income from Basic Financial Contributions (Core), mainly from Voting Participants and will earn 1.7 M euro in Supplementary Funds.

The draft total Secretariat budget expenses total 5.9 M euros, with nearly 5M euros going towards the WP24 (Figure 1) and the rest for administration and governance. This includes Core and Supplemental Fund expenditures.

`Figure 1`
 
The draft WP24 budget includes expenses for staff salaries, external contractors, and non-salary expenses for meetings and travel.  This reflects expenditures from both Core Supplemental Funds. 50% more total WP activities are enabled by Supplemental Funds. Two-thrds of the WP24 expenses are staff salaries (Figure 2).

`Figure 2`

All four Priority Area budgets include costs for staff salary, external contracts, and non-salary expenses such as meetings and travel. The largest expense in all Priority Areas is staff salary. The expected of WP expenses are highest for Priority Areas 2 and 3 (Figure3).

`Figure 3`
