[[introduction]]
== Introduction 

This is the draft of the second annual GBIF Work Programme and annual update to Implementation Plan 2023–2027 (WP24), to be presented under the Strategic Framework for 2023-2027. The overall aim is to focus on the key outcomes that can be expected from GBIF’s work linking them to the four priority areas set out in the Strategic Framework.

The Work Programmes of the Implementation Plan 2023–2027 are less granular than in previous implementation plans, with an emphasis on what will be delivered and achieved, enabling the Governing Board to assess whether implementation is on track. Specific tasks, events or contracts are presented as indicative only, and the intention is to enable flexibility in the means of achieving the proposed outcomes, both within the Secretariat and through the collective efforts of GBIF’s nodes and partners.
Each priority area contains up to four designated activities, as well as ongoing activities presenting work that continues across the five-year implementation plan. There has only been a slight change to the activity areas in 2024. One activity area has been closed and two have been reworded to better reflect the indicative tasks. 
Some indicative tasks are the same as in 2023 because they require multi-year efforts to achieve the projected outcomes. Many new indicative tasks are presented in this work programme. Therefore, the activity areas and indicative tasks should be viewed through a five-year time frame as we work to achieve the overall mission of the 2023–2027 Strategic Framework.
The 2024 budget funds the WP24 and is a separate document. Many indicative tasks described in WP24 have activities, such as external contracts and workshops, funded from core participant funding. These expenses are noted in the WP24. Please refer to the detailed  2024 Budget document for a budget overview and a guide to financial details. The budget also contains details on the income and expenses of supplementary funds —that is, funds beyond the basic financial contributions from GBIF’s Voting Participants. These supplementary funds have increased the scope of the activities of WP24.





*Joe Miller*
Executive Secretary
